In [2]:
import pandas as pd

In [4]:
df = pd.read_csv("../data/spam.csv")
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [5]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [6]:
df['spam']=df['Category'].apply(lambda x: 1 if x=='spam' else 0)
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message,df.spam,test_size=0.25)

In [11]:
X_train.values

array(['Buy Space Invaders 4 a chance 2 win orig Arcade Game console. Press 0 for Games Arcade (std WAP charge) See o2.co.uk/games 4 Terms + settings. No purchase',
       'Call to the number which is available in appointment. And ask to connect the call to waheed fathima.',
       "The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free",
       ...,
       'Hello. They are going to the village pub at 8 so either come here or there accordingly. Ok?',
       'Hey i will be late ah... Meet you at 945+',
       "Am I the only one who doesn't stalk profiles?"], dtype=object)

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_count = v.fit_transform(X_train.values)
v.get_feature_names_out()

array(['00', '000', '000pes', ..., 'zouk', 'èn', '〨ud'], dtype=object)

In [17]:
X_train_count.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [18]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB()

In [19]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = v.transform(emails)
emails_count

<2x7588 sparse matrix of type '<class 'numpy.int64'>'
	with 22 stored elements in Compressed Sparse Row format>

In [20]:
model.predict(emails_count)

array([0, 1])

In [21]:
X_test_count = v.transform(X_test)
model.score(X_test_count, y_test)

0.9849246231155779

Sklearn Pipeline

In [22]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [23]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [24]:
clf.predict(emails)

array([0, 1])

In [25]:
clf.score(X_test,y_test)

0.9849246231155779

Exercise

In [27]:
from sklearn import datasets
wine = datasets.load_wine()

In [28]:
dir(wine)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [30]:
wine.data

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [35]:
df = pd.DataFrame(data=wine.data, columns=wine.feature_names)
df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [34]:
#df['target'] = wine.target
#df

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  target  
0                            3.92   1065.0       0  
1                            3.40   1050.0       0  
2                            3.17   1185.0       0  
3                            3.45   1480.0       0  
4                            2.93    735.0       0  
..                            ...      ...     ...  
173                          1.74    740.0       2  
174                          1.56    750.0       2  
175                          1.56    835.0       2  
176                          1.62    840.0       2  
177                          1.60    560.0       2  

[178 rows x 14 columns]

In [38]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df, wine.target, test_size=0.25)
X_train

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
111    12.52        2.43  2.17               21.0       88.0           2.55   
147    12.87        4.61  2.48               21.5       86.0           1.70   
127    11.79        2.13  2.78               28.5       92.0           2.13   
103    11.82        1.72  1.88               19.5       86.0           2.50   
46     14.38        3.59  2.28               16.0      102.0           3.25   
..       ...         ...   ...                ...        ...            ...   
119    12.00        3.43  2.00               19.0       87.0           2.00   
140    12.93        2.81  2.70               21.0       96.0           1.54   
75     11.66        1.88  1.92               16.0       97.0           1.61   
57     13.29        1.97  2.68               16.8      102.0           3.00   
81     12.72        1.81  2.20               18.8       86.0           2.20   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
111        2.27                  0.26             1.22             2.00  0.90   
147        0.65                  0.47             0.86             7.65  0.54   
127        2.24                  0.58             1.76             3.00  0.97   
103        1.64                  0.37             1.42             2.06  0.94   
46         3.17                  0.27             2.19             4.90  1.04   
..          ...                   ...              ...              ...   ...   
119        1.64                  0.37             1.87             1.28  0.93   
140        0.50                  0.53             0.75             4.60  0.77   
75         1.57                  0.34             1.15             3.80  1.23   
57         3.23                  0.31             1.66             6.00  1.07   
81         2.53                  0.26             1.77             3.90  1.16   

     od280/od315_of_diluted_wines  proline  
111                          2.78    325.0  
147                          1.86    625.0  
127                          2.44    466.0  
103                          2.44    415.0  
46                           3.44   1065.0  
..                            ...      ...  
119                          3.05    564.0  
140                          2.31    600.0  
75                           2.14    428.0  
57                           2.84   1270.0  
81                           3.14    714.0  

[133 rows x 13 columns]

In [40]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train,y_train)

GaussianNB()

In [42]:
model.score(X_test, y_test)

0.9555555555555556

In [44]:
model.predict(X_test)

array([0, 1, 0, 0, 2, 1, 0, 0, 2, 1, 1, 1, 2, 0, 1, 2, 0, 0, 1, 2, 0, 2,
       1, 2, 0, 2, 1, 2, 1, 0, 1, 1, 1, 1, 0, 1, 0, 2, 0, 1, 1, 2, 1, 1,
       0])

In [45]:
y_test

array([0, 1, 0, 0, 2, 1, 0, 0, 2, 1, 1, 1, 2, 0, 1, 2, 0, 0, 1, 2, 0, 2,
       1, 2, 1, 2, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 2, 0, 1, 1, 2, 1, 1,
       0])

In [41]:
model_mnb = MultinomialNB()
model_mnb.fit(X_train,y_train)

MultinomialNB()

In [43]:
model_mnb.score(X_test, y_test)

0.8666666666666667

In [46]:
model.predict(X_test)

array([0, 1, 0, 0, 2, 1, 0, 0, 2, 1, 1, 1, 2, 0, 1, 2, 0, 0, 1, 2, 0, 2,
       1, 2, 0, 2, 1, 2, 1, 0, 1, 1, 1, 1, 0, 1, 0, 2, 0, 1, 1, 2, 1, 1,
       0])

In [47]:
y_test

array([0, 1, 0, 0, 2, 1, 0, 0, 2, 1, 1, 1, 2, 0, 1, 2, 0, 0, 1, 2, 0, 2,
       1, 2, 1, 2, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 2, 0, 1, 1, 2, 1, 1,
       0])